/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Programa.Pjuego;
import java.awt.TextField;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author john_
 */
public final  class Nivel1 extends javax.swing.JFrame {
    
    private    Pjuego L= new Pjuego();
    private boolean CUp = false;
    private ImageIcon img1;
    private ImageIcon img2;
    private JButton[] Pbtn = new JButton[2];
    private boolean Primerc = false;
    private  int puntaje1 = 0;
    private TextField p;
 
 
    
    

    /**
     * Creates new form Nivel1
     */
    public Nivel1() {
        initComponents();
         this.setExtendedState(MAXIMIZED_BOTH);
            Ocartas();
    }
    
      /**
     * Creamos el metodo 
     * para cargar las immagenes de 
     * las cartas 
     * aleatoriamente 
     */
    public void Ocartas(){
    
    int [] car = L.getCardNumbers();
        Bot1.setDisabledIcon(new ImageIcon(getClass().getResource("../Imagenes/n"+car[0]+".jpeg")));
        Bot2.setDisabledIcon(new ImageIcon(getClass().getResource("../Imagenes/n"+car[1]+".jpeg")));
        Bot3.setDisabledIcon(new ImageIcon(getClass().getResource("../Imagenes/n"+car[2]+".jpeg")));
        Bot4.setDisabledIcon(new ImageIcon(getClass().getResource("../Imagenes/n"+car[3]+".jpeg")));
        Bot5.setDisabledIcon(new ImageIcon(getClass().getResource("../Imagenes/n"+car[4]+".jpeg")));
        Bot6.setDisabledIcon(new ImageIcon(getClass().getResource("../Imagenes/n"+car[5]+".jpeg")));
        Bot7.setDisabledIcon(new ImageIcon(getClass().getResource("../Imagenes/n"+car[6]+".jpeg")));
        Bot8.setDisabledIcon(new ImageIcon(getClass().getResource("../Imagenes/n"+car[7]+".jpeg")));
        Bot9.setDisabledIcon(new ImageIcon(getClass().getResource("../Imagenes/n"+car[8]+".jpeg")));
        Bot10.setDisabledIcon(new ImageIcon(getClass().getResource("../Imagenes/n"+car[9]+".jpeg")));
        Bot11.setDisabledIcon(new ImageIcon(getClass().getResource("../Imagenes/n"+car[10]+".jpeg")));
        Bot12.setDisabledIcon(new ImageIcon(getClass().getResource("../Imagenes/n"+car[11]+".jpeg")));
    }
    
    
    
    
    /**
     * Metodo de estados de los botones 
     */
     private void Habilitarbtn (JButton Bot) {
        
        if(!CUp) {
            Bot.setEnabled(false);
            img1= (ImageIcon) Bot.getDisabledIcon();
            Pbtn[0] = Bot;
            CUp = true;
            Primerc = false;
        }
        else {
            Bot.setEnabled(false);
            img2= (ImageIcon) Bot.getDisabledIcon();
            Pbtn[1] = Bot;
            Primerc = true;
            puntaje1 += 20;
            Ganar();
        }
    }
     /**
      * Metodo para comparar 
      * las cartas 
      */
     
     
     private void comparar() {
        if(CUp && Primerc) {
            
            if(img1.getDescription().compareTo(img2.getDescription()) != 0) {
                Pbtn[0].setEnabled(true);
                Pbtn[1].setEnabled(true);
                if(puntaje1> 10 ) puntaje1 -= 10;
             
                
            }
            CUp = false;
        }
    }
    
     
      private void Ganar() {
              
                if(!Bot1.isEnabled() && !Bot2.isEnabled() && !Bot3.isEnabled() && !Bot4.isEnabled() && !Bot5.isEnabled() && !Bot6.isEnabled() && 
                !Bot7.isEnabled() && !Bot8.isEnabled() && !Bot9.isEnabled() && !Bot10.isEnabled() && !Bot11.isEnabled() && !Bot12.isEnabled()) {
                       JOptionPane.showMessageDialog(this, "Felicidades, usted ha ganado. Su puntaje es: " +puntaje1, "GANASTE!!", JOptionPane.INFORMATION_MESSAGE);
                   
                   
                }
      }
     
      
      
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bot1 = new javax.swing.JButton();
        Bot2 = new javax.swing.JButton();
        Bot3 = new javax.swing.JButton();
        Bot4 = new javax.swing.JButton();
        Bot5 = new javax.swing.JButton();
        Bot10 = new javax.swing.JButton();
        Bot9 = new javax.swing.JButton();
        Bot8 = new javax.swing.JButton();
        Bot7 = new javax.swing.JButton();
        Bot6 = new javax.swing.JButton();
        Bot11 = new javax.swing.JButton();
        Bot12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nivel1");
        setBackground(new java.awt.Color(255, 0, 51));
        setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        Bot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta.jpeg"))); // NOI18N
        Bot1.setBorder(null);
        Bot1.setBorderPainted(false);
        Bot1.setFocusPainted(false);
        Bot1.setFocusable(false);
        Bot1.setRolloverEnabled(true);
        Bot1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta2.jpeg"))); // NOI18N
        Bot1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bot1MouseExited(evt);
            }
        });
        Bot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot1ActionPerformed(evt);
            }
        });

        Bot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta.jpeg"))); // NOI18N
        Bot2.setBorder(null);
        Bot2.setBorderPainted(false);
        Bot2.setFocusPainted(false);
        Bot2.setFocusable(false);
        Bot2.setRolloverEnabled(true);
        Bot2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta2.jpeg"))); // NOI18N
        Bot2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bot2MouseExited(evt);
            }
        });
        Bot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot2ActionPerformed(evt);
            }
        });

        Bot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta.jpeg"))); // NOI18N
        Bot3.setBorder(null);
        Bot3.setBorderPainted(false);
        Bot3.setFocusPainted(false);
        Bot3.setFocusable(false);
        Bot3.setRolloverEnabled(true);
        Bot3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta2.jpeg"))); // NOI18N
        Bot3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bot3MouseExited(evt);
            }
        });
        Bot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot3ActionPerformed(evt);
            }
        });

        Bot4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta.jpeg"))); // NOI18N
        Bot4.setBorder(null);
        Bot4.setBorderPainted(false);
        Bot4.setFocusPainted(false);
        Bot4.setFocusable(false);
        Bot4.setRolloverEnabled(true);
        Bot4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta2.jpeg"))); // NOI18N
        Bot4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bot4MouseExited(evt);
            }
        });
        Bot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot4ActionPerformed(evt);
            }
        });

        Bot5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta.jpeg"))); // NOI18N
        Bot5.setBorder(null);
        Bot5.setBorderPainted(false);
        Bot5.setFocusPainted(false);
        Bot5.setFocusable(false);
        Bot5.setRolloverEnabled(true);
        Bot5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta2.jpeg"))); // NOI18N
        Bot5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bot5MouseExited(evt);
            }
        });
        Bot5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot5ActionPerformed(evt);
            }
        });

        Bot10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta.jpeg"))); // NOI18N
        Bot10.setBorder(null);
        Bot10.setBorderPainted(false);
        Bot10.setFocusPainted(false);
        Bot10.setFocusable(false);
        Bot10.setRolloverEnabled(true);
        Bot10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta2.jpeg"))); // NOI18N
        Bot10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bot10MouseExited(evt);
            }
        });
        Bot10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot10ActionPerformed(evt);
            }
        });

        Bot9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta.jpeg"))); // NOI18N
        Bot9.setBorder(null);
        Bot9.setBorderPainted(false);
        Bot9.setFocusPainted(false);
        Bot9.setFocusable(false);
        Bot9.setRolloverEnabled(true);
        Bot9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta2.jpeg"))); // NOI18N
        Bot9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bot9MouseExited(evt);
            }
        });
        Bot9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot9ActionPerformed(evt);
            }
        });

        Bot8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta.jpeg"))); // NOI18N
        Bot8.setBorder(null);
        Bot8.setBorderPainted(false);
        Bot8.setFocusPainted(false);
        Bot8.setFocusable(false);
        Bot8.setRolloverEnabled(true);
        Bot8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta2.jpeg"))); // NOI18N
        Bot8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bot8MouseExited(evt);
            }
        });
        Bot8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot8ActionPerformed(evt);
            }
        });

        Bot7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta.jpeg"))); // NOI18N
        Bot7.setBorder(null);
        Bot7.setBorderPainted(false);
        Bot7.setFocusPainted(false);
        Bot7.setFocusable(false);
        Bot7.setRolloverEnabled(true);
        Bot7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta2.jpeg"))); // NOI18N
        Bot7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bot7MouseExited(evt);
            }
        });
        Bot7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot7ActionPerformed(evt);
            }
        });

        Bot6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta.jpeg"))); // NOI18N
        Bot6.setBorder(null);
        Bot6.setBorderPainted(false);
        Bot6.setFocusPainted(false);
        Bot6.setFocusable(false);
        Bot6.setRolloverEnabled(true);
        Bot6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta2.jpeg"))); // NOI18N
        Bot6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bot6MouseExited(evt);
            }
        });
        Bot6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot6ActionPerformed(evt);
            }
        });

        Bot11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta.jpeg"))); // NOI18N
        Bot11.setBorder(null);
        Bot11.setBorderPainted(false);
        Bot11.setFocusPainted(false);
        Bot11.setFocusable(false);
        Bot11.setRolloverEnabled(true);
        Bot11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta2.jpeg"))); // NOI18N
        Bot11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bot11MouseExited(evt);
            }
        });
        Bot11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot11ActionPerformed(evt);
            }
        });

        Bot12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta.jpeg"))); // NOI18N
        Bot12.setBorder(null);
        Bot12.setBorderPainted(false);
        Bot12.setFocusPainted(false);
        Bot12.setFocusable(false);
        Bot12.setRolloverEnabled(true);
        Bot12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta2.jpeg"))); // NOI18N
        Bot12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bot12MouseExited(evt);
            }
        });
        Bot12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bot1)
                    .addComponent(Bot5)
                    .addComponent(Bot9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Bot2)
                        .addComponent(Bot6))
                    .addComponent(Bot12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bot3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bot4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bot7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bot8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bot10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bot11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bot2)
                    .addComponent(Bot1)
                    .addComponent(Bot3)
                    .addComponent(Bot4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bot7)
                            .addComponent(Bot8)
                            .addComponent(Bot5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bot9)
                            .addComponent(Bot10)
                            .addComponent(Bot11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bot6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bot12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 31, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Los números ");
        jLabel1.setAutoscrolls(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 422, 80));

        jLabel2.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 0));
        jLabel2.setText("¡Encuentre las parejas de los números!...");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 520, 134));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot1ActionPerformed
        Habilitarbtn(Bot1);
    }//GEN-LAST:event_Bot1ActionPerformed

    private void Bot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot2ActionPerformed
        Habilitarbtn(Bot2);
    }//GEN-LAST:event_Bot2ActionPerformed

    private void Bot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot3ActionPerformed
        Habilitarbtn(Bot3);
    }//GEN-LAST:event_Bot3ActionPerformed

    private void Bot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot4ActionPerformed
      Habilitarbtn(Bot4);
    }//GEN-LAST:event_Bot4ActionPerformed

    private void Bot5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot5ActionPerformed
      Habilitarbtn(Bot5);
    }//GEN-LAST:event_Bot5ActionPerformed

    private void Bot6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot6ActionPerformed
        Habilitarbtn(Bot6);
    }//GEN-LAST:event_Bot6ActionPerformed

    private void Bot7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot7ActionPerformed
      Habilitarbtn(Bot7);
    }//GEN-LAST:event_Bot7ActionPerformed

    private void Bot8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot8ActionPerformed
      Habilitarbtn(Bot8);
    }//GEN-LAST:event_Bot8ActionPerformed

    private void Bot9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot9ActionPerformed
        Habilitarbtn(Bot9);
    }//GEN-LAST:event_Bot9ActionPerformed

    private void Bot10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot10ActionPerformed
       Habilitarbtn(Bot10);
    }//GEN-LAST:event_Bot10ActionPerformed

    private void Bot1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot1MouseExited
         comparar();
    }//GEN-LAST:event_Bot1MouseExited

    private void Bot11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot11ActionPerformed
       Habilitarbtn(Bot11);
    }//GEN-LAST:event_Bot11ActionPerformed

    private void Bot12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot12ActionPerformed
        Habilitarbtn(Bot12);
    }//GEN-LAST:event_Bot12ActionPerformed

    private void Bot11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot11MouseExited
         comparar();
    }//GEN-LAST:event_Bot11MouseExited

    private void Bot2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot2MouseExited
         comparar();
    }//GEN-LAST:event_Bot2MouseExited

    private void Bot3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot3MouseExited
         comparar();
    }//GEN-LAST:event_Bot3MouseExited

    private void Bot4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot4MouseExited
         comparar();
    }//GEN-LAST:event_Bot4MouseExited

    private void Bot5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot5MouseExited
        comparar();
    }//GEN-LAST:event_Bot5MouseExited

    private void Bot6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot6MouseExited
        comparar();
    }//GEN-LAST:event_Bot6MouseExited

    private void Bot7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot7MouseExited
        comparar();
    }//GEN-LAST:event_Bot7MouseExited

    private void Bot8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot8MouseExited
         comparar();
    }//GEN-LAST:event_Bot8MouseExited

    private void Bot9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot9MouseExited
        comparar();
    }//GEN-LAST:event_Bot9MouseExited

    private void Bot12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot12MouseExited
         comparar();
    }//GEN-LAST:event_Bot12MouseExited

    private void Bot10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot10MouseExited
        comparar();
    }//GEN-LAST:event_Bot10MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Nivel1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bot1;
    private javax.swing.JButton Bot10;
    private javax.swing.JButton Bot11;
    private javax.swing.JButton Bot12;
    private javax.swing.JButton Bot2;
    private javax.swing.JButton Bot3;
    private javax.swing.JButton Bot4;
    private javax.swing.JButton Bot5;
    private javax.swing.JButton Bot6;
    private javax.swing.JButton Bot7;
    private javax.swing.JButton Bot8;
    private javax.swing.JButton Bot9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}